### ISSUE TITLE
Dependency management support

### ISSUE THREAD

**Issue by cojoj** [czechboy0/XcodeServerSDK#1]
It would be nice to have a dependency management for this SDK and allow users to easily use it in they projects. I think that support for cocoapods and Carthage is required to create a whole new range of possibilities for developers.

**Comment by czechboy0** [comment]
Added CocoaPods support as of [0.0.4](https://github.com/czechboy0/XcodeServerSDK/tree/0.0.4). Feel free to send a PR with Carthage support.
