### ISSUE TITLE
Use Nimble for test matchers

### ISSUE THREAD

**Issue by czechboy0** [czechboy0/XcodeServerSDK#105]
Let's modernize & simplify our tests with https://github.com/Quick/Nimble

**Comment by cojoj** [comment]
In that case it'd be advisable to change the whole testing approach to **BDD** and use both Quick and Nimble... I don't know if they support **code coverage**?

**Comment by cojoj** [comment]
And one more thing from me...
If we're going to rewrite test cases we should fix some issues at the same time, so we don't speed up and leave some tech debt. I mean, we have:
- #98 
- #81 
- #40 (one last tiny piece of feature... 🙏)

**Comment by czechboy0** [comment]
Actually I don't want to use Quick. I want to keep using vanilla XCTest so that we can still run separate tests one by one etc. I just want to use Nimble matchers instead of `XCTestAssertEqual...`. Using all the way up to Quick takes away too many good Xcode and XCTest features for my taste. 

Agreed that we should fix those issues as well, but let's take it one step at a time.

**Comment by cojoj** [comment]
Makes sense 👍
