### ISSUE TITLE
Crash - no available platforms on Xcode Server

### ISSUE THREAD

**Issue by czechboy0** [czechboy0/XcodeServerSDK#114]
Happens on certain instances of Xcode Server

```
Application Specific Information:
fatal error: Couldn't find intended platform in list of platforms: []!: file /Users/honzadvorsky/Documents/Buildasaur/Pods/XcodeServerSDK/XcodeServerSDK/API Routes/XcodeServer+Bot.swift, line 172
```

Originally reported by @valeriomazzeo in https://github.com/czechboy0/Buildasaur/issues/143.

---

Solution:
- [x] instead of crashing, just generate an error describing this issue and fail the bot-creation process
- [ ] make sure Buildasaur shows this error in the UI

**Comment by cojoj** [comment]
You rather want it to return some kind of `completion` or simply `throw`?

**Comment by cojoj** [comment]
I think if we want to fail bot creation process we should stick with `throw` 😉 I'll try to do something with this issue today...

**Comment by czechboy0** [comment]
It's an asynchronous process so I don't think `throw` will work. Just
creating an error and completing should be enough.

**Comment by cojoj** [comment]
`private func replacePlaceholderPlatformInBot(bot: Bot, platforms: [DevicePlatform])` is the method in which the `fatalError`s are called... Looks to me like it's totally synchronous. The bot creation isn't synchronous... Anyway, you suggest returning of the optional `ErrorType` from this method? Seems legit 😉

**Comment by czechboy0** [comment]
Oh right, I was talking about the big picture of the whole process. Makes
perfect sense here to throw, sorry. What I meant is that that error should
then be fed into the failing completion block.

**Comment by cojoj** [comment]
Communication is always an issue in my case 😜 Great that we're now on the same tracks!
