### ISSUE TITLE
Automatically detect API version

### ISSUE THREAD

**Issue by czechboy0** [czechboy0/XcodeServerSDK#12]
Responses from Xcode Server return in their headers the API version, so instead of having to initialize the `Config` file with the API version, we should make one call in the beginning to find out which version we're talking to and save that in memory inside of `XcodeServer`.

**Comment by cojoj** [comment]
There is this little `/ping` endpoint which don't require much and will probably give us what we need.

**Comment by czechboy0** [comment]
:+1:

**Comment by cojoj** [comment]
You mean this field: `X-XCSAPIVersion`?

**Comment by czechboy0** [comment]
Actually :laughing:, it's not necessary to be able to tell. Silly me.

**Comment by czechboy0** [comment]
See https://github.com/czechboy0/XcodeServerSDK/commit/41bfb8a3f3b0df6a58aa0a2fc722c6091207781e

**Comment by cojoj** [comment]
Just saw it... 😂

**Comment by czechboy0** [comment]
Embarrassingly closing...
