### ISSUE TITLE
Incompatible with Xcode 7.3 beta

### ISSUE THREAD

**Issue by dstarke** [czechboy0/XcodeServerSDK#128]
The Xcode 7.3 beta tools increment the API version number to 9, which causes requests made through this library to fail due to "Version Mismatch".

If I understand the Xcode server API documentation correctly, it appears that the server should be backwards compatible with older versions if you supply the X-XCSAPIVersion header in each request with the version you want, so the version check in this library may be too aggressive.

**Comment by czechboy0** [comment]
Thanks for reporting this. For now you can add the version number here:https://github.com/czechboy0/XcodeServerSDK/blob/d1bfdbb64988c8990e53faed2f09f54693737f96/XcodeServerSDK/XcodeServer.swift#L76
I'll look at a proper fix later (exam period atm)

**Comment by czechboy0** [comment]
I just merged a fix and I'll release a fixed version in a minute (of both XcodeServerSDK and Buildasaur).

**Comment by dstarke** [comment]
Thanks!

**Comment by czechboy0** [comment]
Aight, Buildasaur is fixed here: https://github.com/czechboy0/Buildasaur/releases/tag/v0.6.5 and XcodeServerSDK here: https://github.com/czechboy0/XcodeServerSDK/releases/tag/v0.5.4

Thanks for taking the time to report this, @dstarke! I appreciate it.
