### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by cojoj** [czechboy0/XcodeServerSDK#16]
I'll start writing test suit but I think that it's a good idea to start this from `swift-2` branch and take advantage of test coverage.

I think we can stick to `XCTest` as it works pretty great right now.

One think I want to ask you @czechboy0. Do you think I should create PR after I finish everything/most of the work or create new PR at the beginning of the whole process and allow anyone (with focus on you) to track changes, comment them and suggest changes to keep people more involved into the process?

**Comment by czechboy0** [comment]
I actually prefer a higher volume of smaller pull requests. So feel free to add a couple of tests, pr it, another day add more, create a new pr for that etc.  That makes it easier to track changes and find a good way we want to do this over time. Let's start small.

Yeah let's use swift-2 as our "master" right now and base everything on it - just as you said, to take advantage of all the cool Xcode 7 features. 

So prs should be from temporary branches into swift-2. 

Does that make sense?

**Comment by cojoj** [comment]
Great, so glad that we both have same similar vision 😉

**Comment by czechboy0** [comment]
Here's what I'm thinking (I just created a simple case): https://github.com/czechboy0/XcodeServerSDK/compare/hd/tests_1?expand=1

But basically, I think (at least for the parsing tests, which will be a large portion), we should have JSON files with sample dump of real data from Xcode Server. And in the test, we load the appropriate one, let it create the native Swift object and assert that the fields are what we expect them to be.

No need to always test all fields, we should only assert the field we're testing in each test case (so `id`, `_rev` etc we only test in one common test, but not in all bots tests, for instance).

Take a look at the diff above (sorry, still in Xcode 6/Swift 1.2 format, but you get the gist) and let me know if that looks fine to you.

**Comment by cojoj** [comment]
That's right, we need mock objects - in our case prepared JSON files in test bundle from which we'll create mock object inside tests.

**Comment by cojoj** [comment]
I think I'll sit on think during the weekend but I have no XcodeServer on my personal Mac and probably won't have time tomorrow at work to create some mock JSONs.

Is it possible for you, @czechboy0, to provide some JSON files which will be used is mock objects? It'll be nice to have some JSONs of different bots with different configurations so we can crete Array of them for some tests and also break them to separate bots.

Later we can do the same with integrations...

**Comment by czechboy0** [comment]
Done in #18 for Bots. Most cases are from an Xcode 6 server, but some are from Xcode 7. My worry is it will be too much of a pain to support both in the same codebase. We might need to tidy up support for Xcode 6, make the last pod version and then go into the beauties of the future with just Xcode 7.

I mean, that's the first **officially** supported version. But people will still be able to use the old pod version if they want Xcode 6 support.

**Comment by czechboy0** [comment]
@cojoj Btw install Xcode Server on your personal Mac as well, it'll help you develop and test much faster. Just get OS X Server from the developer portal and start it. Takes minutes.

**Comment by cojoj** [comment]
@czechboy0 I agree with you about **Xcode 6** support. BTW, my opinion on this topic is like: _Apple officially allows this from Xcode 7, so let's focus on Xcode 7_.

I guess that everyone interested in using this framework will realize that we want to focus on newest tools and they'll probably use newest tools as well.

**Comment by czechboy0** [comment]
I made that change to the readme here: https://github.com/czechboy0/XcodeServerSDK/commit/0f31d7b6419f4557c8ee104cc690f00aa7c1ae24 Let's close this for now as it's too high-level for our work going forward.
