### ISSUE TITLE
Add basic header documentation

### ISSUE THREAD

**Issue by czechboy0** [czechboy0/XcodeServerSDK#19]
Yeah. Should do that.

**Comment by cojoj** [comment]
I can see **Markdown**... **Markdown** everywhere 😉

Yes, for framework like this it's necessary to have header documentation. Especially that Cocoapods has recently added _ratio_ and you can see the _completeness_ on their website.

I suggest adding header docs while completing #16. It'll be easier to manage everything.

**Comment by esttorhe** [comment]
I added some header docs to `XcodeServerConfig` on #32

**Comment by czechboy0** [comment]
:+1:

**Comment by cojoj** [comment]
As @esttorhe has explained, there are some compatibility advantages of using `///` insted of `/***/`. @czechboy0 what's your opinion on that matter? You have to choose one style and we all should follow it.

**Comment by czechboy0** [comment]
This got resolved here: https://github.com/czechboy0/XcodeServerSDK/pull/32#discussion_r33121539 It looks like the issue which broke `/***/` in beta 1 is now resolved in beta 2. So we're keeping the javadoc format.

**Comment by czechboy0** [comment]
As with #16, this work has started and we're gradually going ahead with this. I'll create milestones for these sub-projects so that we know when we have 100% header documentation coverage and close to 100% test coverage.
