### ISSUE TITLE
New Xcode API

### ISSUE THREAD

**Issue by cojoj** [czechboy0/XcodeServerSDK#2]
While watching **Platforms state of the union** I've heard that from the new versions there'll be official JavaScript API for interacting with Xcode. I haven't watched new session about server (will do ASAP).

If this is true, how will it impact existing code? Maybe no more reverse engineering will be needed to develop this project? 😏

I'm more interested in adding missing functionalities and provide support for all endpoints included in Xcode.

**Comment by czechboy0** [comment]
The current state should support both the Xcode 6 and 7 APIs. They haven't actually changed it to the original, reversed engineered version.

And I think you're looking for [this video](https://developer.apple.com/videos/wwdc/2015/?id=410).

**Comment by cojoj** [comment]
This video was **super cool** but I wonder if they'll provide some docs for the **API**.

For now they _officially_ support those endpoints:

| Type | Path | Description |
| --- | --- | --- |
| GET | `/bots` | List bots on server |
| POST | `/bots` | Create a new bot |
| GET | `/bots/(id)` | Retrieve a bot by ID |
| PATCH | `/bots/(id)` | Update a bot’s configuration |
| GET | `/bots/(id)/integrations` | Get the most recent integrations for a bot |
| POST | `/bots/(id)/integrations` | Enqueue a new integration |
| GET | `/integrations` | List integrations on server |
| GET | `/integrations/(id)` | Retrieve an integration by ID |
| GET | `/integrations/(id)/commits` | List the commits included in an integration |
| GET | `/integrations/(id)/issues` | List the build issues produced by an integration |
| GET | `/devices` | List devices connected to server |
| GET | `/repositories` | List hosted repositories on server |
| POST | `/repositories` | Create a new hosted repository |

It's easy to handle `GET` endpoints - actually there's nothing to handle but when taking into account some `POST` ones we're back to **trials and errors**. I see they haven't updated the [Xcode Server and Continuous Integration Guide](https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/xcode_guide-continuous_integration/index.html#//apple_ref/doc/uid/TP40013292-CH1-SW1) to provide anything about API.

**Comment by czechboy0** [comment]
Yeah I heard they'll provide proper documentation with Seed 2 or 3 of Xcode 7, so we just need to wait a couple of weeks. But when it comes to functionality, **nothing has changed** (with one exception - fingerprint validation) when it comes to the APIs. So all these calls that I originally reverse-engineered for Buildasaur still work well. Thus there should be not much additional work to get everything properly compatible with Xcode 7.

Btw, I'm sure you know, but you can actually see all the APIs available in `/Applications/Xcode.app/Contents/Developer/usr/share/xcs/xcsd/routes/routes.js` in Xcode 6 and in the files in folder `/Applications/Xcode-beta.app/Contents/Developer/usr/share/xcs/xcsd/routes/` in Xcode 7. They just tidied the files in Xcode 7 but didn't change the API calls themselves (thank goodness).

**Comment by cojoj** [comment]
I think that was their point to first hide it, maintain it and if it' ready than release it and tell devs - look what a great tool we give you! 😉

I meant that a clean documentation with a list of required fields will be helpful so we don't have to struggle each time with blueprints and over bloating JSON we generate.

**Comment by czechboy0** [comment]
Sure, but the stuff we send now is exactly what Xcode sends when talking to Xcode Server. That's how I reverse-engineered it, by using a proxy and observing the payload that gets sent :smile: 

I sure hope there will now be a larger community around integrating with Xcode Server's API, because it's a pretty awesome tool. And by making the API public, many more people will find it worth while to look into it (hopefully, time will tell).

**Comment by czechboy0** [comment]
Closing for now, as there's no next step we can take at the moment :)
