### ISSUE TITLE
iOS target missing

### ISSUE THREAD

**Issue by esttorhe** [czechboy0/XcodeServerSDK#24]
I noticed on the `podspec` that there's support for `iOS` (which makes sense because the files are architecture independent as far as I could see) but the project lacks an `iOS` target which makes it impossible to use on an `iOS` project using `Carthage` because it will only build the `OS X` framework.

Hopefully I'll be able to easily create an `iOS` target and will issue a `PR` with said fix later today but wanted to leave this issue to easily track it down.

:bow:

**Comment by cojoj** [comment]
Great, waiting for PR!

Yes, the main idea is to create platform independent **SDK** but we don't have many other things to test that everything works correctly and we're focusing on the core of the whole framework at the moment.

@esttorhe maybe you have idea how to import _this_ framework into Playground residing in `.xcworkspace`?

**Comment by esttorhe** [comment]
I think I have an idea or two for the `Playground` import; although I think it would be worth opening a separate issue for that perhaps?

**Comment by cojoj** [comment]
Sure, you can create new issue but we've discussed this thing with @czechboy0 somewhere...

**Comment by czechboy0** [comment]
Fixed in #25.
