### ISSUE TITLE
Tidying the directory

### ISSUE THREAD

**Issue by cojoj** [czechboy0/XcodeServerSDK#3]
To keep everything clean I suggest dividing all files to separate directories eg. Bot is a big object with smaller pieces like Trigger and so on.

It would be nice to have the grouped in the proper way. I think this can be achieved only by laborious JSON analysis but IMHO it'll pay off in future.

**Comment by czechboy0** [comment]
I agree on both points. Feel free to fork and do this, splitting each object into its own file and putting it all into a better folder structure.

**Comment by czechboy0** [comment]
Part of #15.
