### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by czechboy0** [czechboy0/XcodeServerSDK#30]
In #1 @cojoj mentioned Carthage support. Let's look into how much would be required to properly support it, test out that our framework works both in iOS and OS X projects and if everything works, let's add the proper badge into our readme: [![Carthage compatible](https://img.shields.io/badge/Carthage-compatible-4BC51D.svg?style=flat)](https://github.com/Carthage/Carthage)

@cojoj, do you want to take care of this?

**Comment by cojoj** [comment]
I really have no experience with Carthage but can take a look at this issue 😉
As far as I know, the should be safe and sound with Carthage support at the current state but...

**Comment by cojoj** [comment]
Here's how it looks like...

When I create OS X application from `master`, which is `0.0.4` right now and supports Swift 1.2 I'm able to use everything without any complications and the whole process is pretty straight forward so I think that if we're telling people `master` is our working code we can put the badge in `README`.

I've tried to use `swift-2` branch and integrate it with iOS application, unfortunately, without luck. Carthage built everything with no issues but when it became to importing framework into project Xcode was telling me that it cannot find module XcodeServerSDK...

I'll try to integrate `swift-2` with OS X application and let you know about the results.

**Comment by cojoj** [comment]
OS X El Capitan and `swift-2` is working like a charm... We're missing iOS support at the moment 😓

![](http://media4.giphy.com/media/5xtDartpELLnXKkhytW/giphy.gif)

**Comment by cojoj** [comment]
![screen shot 2015-06-22 at 12 09 01](https://cloud.githubusercontent.com/assets/4522407/8279778/8400944c-18d7-11e5-8416-8e983c874f10.png)

@esttorhe any ideas❓

**Comment by cojoj** [comment]
Searching, searching, searching and... Found it. Seems like iOS projects in Xcode 7.0 has some sort of issue/bug and you need to manually provide _Framework search paths_. I found the solution in [this issue](https://github.com/Carthage/Carthage/issues/536).

So, after specifying Build settings → Framework search paths → `$(PROJECT_DIR)/Carthage/Build/iOS/` I get it working in iOS Application.

I know, **picture or didn't happen**...
![screen shot 2015-06-22 at 12 34 26](https://cloud.githubusercontent.com/assets/4522407/8280247/b7243d3e-18db-11e5-9b1c-264f7eb82d2b.png)

---

Another thing about Carthage... Now, everytime you call `carthage update` you're downloading source code and building it locally. We can skip this part by **tagging stable releases** what is pointed in Carthage's _README_.
One more thing, @czechboy0 need to add `DevelopmentTeam`, `CODE_SIGN_IDENTITY` and `PROVISIONING_PROFILE` to iOS target.

**Comment by esttorhe** [comment]
Also remember if you are rolling `Carthage` support to add the `Build Phase` that executes Carthage's script that copies the frameworks to the target or if you want to; create a `Copy Phase` that moves the dependencies to the «Frameworks» «folder»

**Comment by cojoj** [comment]
@esttorhe I've added the script to build phase but this only apply to iOS version and still was throwing `No module` error. As I've mentioned above, there's some sort of bug in current beta (confirmed by Apple) with copying of third party framework which can be fixed by providing path manually.

To sum up, **we have no power here!**

**Comment by esttorhe** [comment]
yeah; I wasn't implying that was the issue; just wanted to remind anyone reading this :eyes: that you need to execute the script or add the copy phase 

---

Edit: Would be good to add a link to where Apple «documented» the confirmed bug; perhaps an openradar link or something else

**Comment by cojoj** [comment]
Ha, that's a great question... I found this in Carthage's issue and guy was caliming that he asked Apple engineer about this during DubDub, so... 😜

**Comment by esttorhe** [comment]
Just wanted to throw my 2 cents in here.

I don't think there's a need for the addition of `DevelopmentTeam`, `CODE_SIGN_IDENTITY` and/or `PROVISIONING_PROFILE` to support `Carthage`.

Also; I think we are good to go to add the badge on the `README`.

Proof that this is working is a current project of mine https://github.com/esttorhe/Watch_BotLauncher

That's using my ᴡᴀᴛᴄʜ branch of `XcodeServerSDK` with `Carthage` and I'm currently including `iOS` and `ᴡᴀᴛᴄʜ` dependencies into my targets.

PS. Albeit; there's no code in my project yet (first I needed some things from this framework; e.g.: `iOS` and `ᴡᴀᴛᴄʜ` support ;) ) but you can see that it downloaded the source and compiled accordingly.

**Comment by czechboy0** [comment]
All works, according to @esttorhe. We also declare it in our readme as of #34.

**Comment by esttorhe** [comment]
See; another great thing about `CHANGELOG`; know who to blame when something doesn't work :joy:

**Comment by czechboy0** [comment]
Yup, I was very careful with the wording above to put you and you alone in the spotlight :dancer:

**Comment by cojoj** [comment]
So, we're officially supporting **Carthage** buth where's the **badge**? 😜

![](http://media1.giphy.com/media/720g7C1jz13wI/giphy.gif)
