### ISSUE TITLE
Add `throw` method to TestUtils

### ISSUE THREAD

**Issue by esttorhe** [czechboy0/XcodeServerSDK#36]
As mentioned by @czechboy0 here - https://github.com/czechboy0/XcodeServerSDK/pull/32#discussion_r33181938

It would be great to have a convenience method where we can pass a throwing function, the expected `ErrorType` and then printout if the thrown error matches the one passed or fail otherwise

**Comment by cojoj** [comment]
I'm on it... 😉

**Comment by czechboy0** [comment]
Fixed by #41.
