### ISSUE TITLE
Different amount of tests on different platform

### ISSUE THREAD

**Issue by cojoj** [czechboy0/XcodeServerSDK#42]
@esttorhe, while you were creating targets you told us that both OS X and iOS will use the same test target. Could you explain something to me? (I have no idea how it works)

Right now, when I run tests on iOS I get:
![screen shot 2015-06-25 at 13 01 50](https://cloud.githubusercontent.com/assets/4522407/8353019/6044665e-1b3a-11e5-8108-75f78e0e3796.png)
Which was fine until I switched to OS X and run tests again which produced something different:
![screen shot 2015-06-25 at 13 00 03](https://cloud.githubusercontent.com/assets/4522407/8352991/1dea575a-1b3a-11e5-9713-2b77fc42b4b5.png)

---

I wonder if it's normal that different targets shows us different test coverage? If you'll tell me that this is totally normal I'm fine... I just have no experience in this matter and that made me thinking 😉

**Comment by czechboy0** [comment]
I saw the same thing yesterday. Just go through all the files in the test target and make sure that they are all contained in both the OS X and iOS test targets. The way XCTest works is that it pulls all contained `XCTestCase` subclasses in the project and runs them. If you leave one out, it will still compile just fine, it just won't run those tests.
