### ISSUE TITLE
Move API calls to separate files

### ISSUE THREAD

**Issue by cojoj** [czechboy0/XcodeServerSDK#47]
At the moment, all API calls are stored in `XcodeServer.swift`. It'd be advisable to move the to separate files and make `extension`s from them as the number of API calls may increase in the future.

I suggest separating them by _type_ eg. `XcodeServer+Bots` will store all **Bot** related API calls, `XcodeServer+Integrations` will handle **Integration** and so on...

I don't know what's the proper naming convention and used well know convention from Objective-C. We can stick to this or decide on different style.

---

This issue is **blocked** until #44 is completed as this one may introduce some merge conflicts.

**Comment by cojoj** [comment]
@czechboy0 please hold with work in `XcodeServer` class as I'm planning to apply proposed changes in this issue. I'll probably do it today.

It's already a pain in the ass working with `XcodeServer` class in #48 so it's high time to do some clean up! 😉

**Comment by czechboy0** [comment]
Go for it, I don't have any outstanding work on a branch (a rare moment, use it). I was working on Buildasaur the other day, migrating that beast to Swift 2.

**Comment by czechboy0** [comment]
Another one: #55.

**Comment by cojoj** [comment]
Platform and Device added here: #57

**Comment by czechboy0** [comment]
Finished by #58.
