### ISSUE TITLE
Testing public/internal/private methods

### ISSUE THREAD

**Issue by cojoj** [czechboy0/XcodeServerSDK#52]
I assume that `public` is in every `XcodeServerSDK` class because of Swift 1.2 leftovers? I mean from **testing** point of view. But now, with Swift 2 we were blessed with this beautiful `@testable` annotation, so why not _Zoidberg_?

IMHO, classes like `JSON`, `HTTPUtils` and some more are not meant to be used out of `internal` scope, so we definitely can remove `public` access. **Why do you think?**

**Comment by czechboy0** [comment]
Yes. I'm even tempted to make **everything** private and then make what needs to be `internal` and `public`, so that we have a minimal public interface. Can you use `@testable` on `private` methods as well? Or is it just for `internal`?

**Comment by cojoj** [comment]
Just for `internal`s... 😭
I even started this [twitter conversation](https://twitter.com/cojoj/status/589519213901021184) once.

**Comment by czechboy0** [comment]
Ok, so let's do this: keep indirectly tested methods as `private` and directly tested ones as `internal` or `public`. In a way treat `internal` and `public` as things you'd put in a header file. **But**, always default to `internal` and only make it `public` iff you have a usecase outside of the current module.

And we will try to test all `internal` and `public` methods. So this task is mainly about _removing_ the `public` modifier to make it `internal` again. Does that make sense?

**Comment by cojoj** [comment]
Yes sir, I think that's the right way! Now, **Beats1** and get back to work 😉

**Comment by czechboy0** [comment]
Haha same here. Loving the London style that's on right now.

**Comment by cojoj** [comment]
Oh man... Wish I'm in London right now 🇬🇧 Love this city so much 😻

**Comment by czechboy0** [comment]
It's fucking boiling here right now though. :sweat:

**Comment by cojoj** [comment]
Even though... 😆
