### ISSUE TITLE
CocoaPods now supports ᴡᴀᴛᴄʜ 

### ISSUE THREAD

**Issue by esttorhe** [czechboy0/XcodeServerSDK#60]
It looks like CP now supports native ᴡᴀᴛᴄʜ frameworks on the ß release (https://github.com/CocoaPods/CocoaPods/pull/3681)

Should be change the icon to something more like «:warning: *Supported on CP on the --pre release ß»
Or something like that??

Also here's a link to an example library using this functionality: https://github.com/neonichu/native-watchOS-example

**Comment by czechboy0** [comment]
Sure, send a PR with a change to the readme!

**Comment by czechboy0** [comment]
Also, we already support watchOS in our podspec!

**Comment by esttorhe** [comment]
:joy: I forgot you pre-added it for Boris :joy:

**Comment by czechboy0** [comment]
Yup, we're just so forward-thinking. We should even declare support for the AppleTV SDK and Apple CarOS.

**Comment by esttorhe** [comment]
:joy: 

:car: & :tv: forward-compatibility support ;)
