### ISSUE TITLE
New name for this project! [POLL]

### ISSUE THREAD

**Issue by czechboy0** [czechboy0/XcodeServerSDK#66]
I created an organization [Buildasaurs](https://github.com/buildasaurs) for all these little monsters. Maybe a more appropriate name for this project might be in order? 
- Xcodesaur?
- XcodeServersaur?
- XCsaur?
- XCSaur?
- XcodeServo?
- ?
- profit

Vote with your comments.

**Comment by cojoj** [comment]
I'll stick with my first proposal - **XCSKit**...

But if I have to choose from yours I'd pick **XCSaur**. Would be nice to have a shorter name 😀

**Comment by czechboy0** [comment]
:+1:

**Comment by czechboy0** [comment]
Hmm don't think we're reasonable going to change the name right now. Braaaaand identity would be hurt a bit ;-)
