### ISSUE TITLE
Podfile parsing error

### ISSUE THREAD

**Issue by cojoj** [czechboy0/XcodeServerSDK#73]
I've pulled new things from repo and wanted to call `pod install` and there's some kind of _parsing error_. I haven't investigated it yet but here's the output, so feel free to have a look:

``` bash
[!] ERROR: Parsing unable to continue due to parsing error:
contained in the file located at /Users/cojoj/Developer/XcodeServerSDK/Podfile.lock
PODS:
  - BuildaUtils (0.0.4)
  - DVR (0.0.2-czechboy0)

DEPENDENCIES:
  - BuildaUtils (= 0.0.4)
  - DVR (from `https://github.com/czechboy0/DVR.git`, tag `v0.0.2-czechboy0`)

EXTERNAL SOURCES:
  DVR:
    :git: https://github.com/czechboy0/DVR.git
    :tag: v0.0.2-czechboy0

CHECKOUT OPTIONS:
  DVR:
    :git: https://github.com/czechboy0/DVR.git
    :tag: v0.0.2-czechboy0

SPEC CHECKSUMS:
  BuildaUtils: 88917cac8b0248c792c8d0ff269b24870d36903f
  DVR: c252cd3f4a88f6a3a49f0d66305335951a0aa133

COCOAPODS: 0.38.0.beta.2
```

**Comment by cojoj** [comment]
Looks like some guys faced same issue and I found this: https://github.com/CocoaPods/CocoaPods/issues/3597#issuecomment-107402868

**Comment by czechboy0** [comment]
Weird. Just to sync up, I'm on CocoaPods 0.38.0 (the recent release).

I tried deleting the whole Pods folder and Podfile.lock and running `pod install` again and everything worked fine. Have you tried that?

**Comment by cojoj** [comment]
Okey, no problem with `Podfile.lock` but with `gem`s on my machine 😬

If anyone **ever** face the same issue, first check `psych` gem... It's responsible for parsing yml's used in `Podfile.lock` and if you _install_ the wrong version - oh boy, you're f****ed!

**Hot fix**

``` bash
sudo gem uninstall psych
```

``` bash
sudo gem install psych -v 2.0.5
```

![](http://media2.giphy.com/media/SWVeYE5m6QVIQ/giphy.gif)

**Comment by czechboy0** [comment]
:+1: Glad you got it working.

**Comment by hanksudo** [comment]
@cojoj install 2.0.5 of psych also resolve my problem, thanks!
