### ISSUE TITLE
Date from array

### ISSUE THREAD

**Issue by cojoj** [czechboy0/XcodeServerSDK#78]
@czechboy0 I can't find this anywhere in code so I'll simply ask.
In some responses we're getting **date** but in form of array of components. Didiyou write a method or extension for handling this?
I only found `dateForKey()` and `optionalDateForKey()` but they work with `String`s.

We need something to get this array by calling `arrayForKey()` and return `NSDateComponents` or date formatted `String`.

Got any hints how you want it to be implemented? Here are my ideas:
- add new method to JSON which will return `NSDate`
- add `extension` to `NSArray` which will create `NSDate` or `NSDateComponents` or `String`

In any case we'll have to manually take fields from`Array` and put them in `NSDateComponents` like:

``` swift
let components = NSDateComponents()

components.year = array[0]
components.month = array[1]
components.day = array[2]
components.hour = array[3]
components.minute = array[4]
components.second = array[5]
```

Which kind of sucks...
What's more, `Array` of components we get from XCS has 7 fields and I wonder what is the 7th one... It doesn't look like a timezone... Nanoseconds?

**Comment by cojoj** [comment]
The old one [XCS] returns `Array` of 6 `Int`s but the new one has 7...

**Comment by cojoj** [comment]
Confirmed 👌

7th field is a time is same as in `String` version, so it's `SSSZZZZ`.

In that case we can convert `[Int]` to `String` and pass it to the regular method from `JSON.swift`. That way we'll save some memory as calendar calculations are expensive.

**Comment by czechboy0** [comment]
If that works (would probably warrant a test case for both Xcode 6 and 7)
then :+1:

Good job reverse engineering it ;) That's how we do things here!

**Comment by czechboy0** [comment]
Fixed in https://github.com/buildasaurs/BuildaUtils/pull/1
