### ISSUE TITLE
XcodeServerEndpoints refactoring proposition

### ISSUE THREAD

**Issue by pmkowal** [czechboy0/XcodeServerSDK#79]
Hi guys, recently I was playing a little bit with Xcode Server and I would be glad to help you i.e.  increasing test coverage.

After look at the project, I thought it would be good to test e.g. `endpointURL` method in the `XcodeServerEndpoints` class. But since it is a private method, I would suggest to move this method to a seperate class and make this method internal. What do you think?

**Comment by czechboy0** [comment]
Hi @pmkowal,

thanks! That would be great if you could help out. Yeah it makes sense to make `endpointURL` internal (just remove `private`), but I don't think you need to move it to another class.

**Comment by pmkowal** [comment]
@czechboy0 ok, so I will do it as you proposed.
I just thought it would be good to share the responsibility of `creating requests` and `providing endpoints` between seperate classes.
