### ISSUE TITLE
BuildaUtils for iOS target

### ISSUE THREAD

**Issue by cojoj** [czechboy0/XcodeServerSDK#89]
I've tried to run today `XcodeServerSDK`'s iOS target I get this rather strange error:

![screen shot 2015-07-29 at 10 43 52](https://cloud.githubusercontent.com/assets/4522407/8953470/faf1d272-35de-11e5-9aad-02df0dadf15e.png)

It looks like our `Podfile` is linking wrong `BuildaUtils` target. Any idea what's wrong?

**Comment by czechboy0** [comment]
Weird: https://github.com/CocoaPods/Specs/blob/master/Specs/BuildaUtils/0.0.8/BuildaUtils.podspec.json#L15

**Comment by cojoj** [comment]
I know, I know... I'm reinstalling Xcode (this crazy lil bastard) and I'll check on this one more time!

**Comment by cojoj** [comment]
Nope, nothing... Still getting this error.

Take a look at this: https://github.com/Alamofire/Alamofire/issues/106

**Comment by czechboy0** [comment]
Delete derived data?

**Comment by czechboy0** [comment]
Hmm I'm still confused. How can we change the `podspec` to work for iOS as well? I thought that would already be working now.

**Comment by cojoj** [comment]
Derieved data deleted, Xcode reinstalled... Nothing seems to help!

**Comment by cojoj** [comment]
@czechboy0 do we have to provide two separate targets? Maybe this is the issue...

**Comment by cojoj** [comment]
When I did modify `Podfile` iOS `targets` to look like:

``` ruby
target 'XcodeServerSDK - iOS' do
    platform :ios, '9.0'
    pod utils_name, utils_version
end

target 'XcodeServerSDK - iOS Tests' do
    platform :ios, '9.0'
    pod utils_name, utils_version
    pod 'DVR', :git => "https://github.com/czechboy0/DVR.git", :tag => "v0.0.3-czechboy0"
end
```

everyting started working for iOS but unexpectedly OS X target fails with:

![zrzut ekranu 2015-07-29 o 21 33 15](https://cloud.githubusercontent.com/assets/4522407/8967789/7626ddb6-3639-11e5-9eb3-3d00cb6432b8.png)

**Comment by czechboy0** [comment]
Damn, this is annoying! Maybe something to file with CocoaPods?

**Comment by cojoj** [comment]
¯_(ツ)_/¯ 

There are many possible scenarios... I think I'd be great if some Cocoapods guru can take a glipse at the project itself and at `Podfile`. Maybe @neonichu 😜

**Comment by neonichu** [comment]
probably deintegration woes, try out https://github.com/kylef/cocoapods-deintegrate and then `pod install` again (see also CocoaPods/CocoaPods#2471)

**Comment by cojoj** [comment]
I did deintegration...
I did add `platform` to each `target`...

😭

**Comment by neonichu** [comment]
How can I repro this?

**Comment by cojoj** [comment]
Just `git clone` this repo and try building it for different targets (OS X, iOS and watchOS) but from `swift-2` branch 😉

Current `Podfile` should fail for iOS and when you specify `platform` it'll fail for OS X.

**Comment by neonichu** [comment]
In this case, you should rather explicitly define the `platform` for each target, like this:

``` diff
diff --git a/Podfile b/Podfile
index eef1f20..19c7bd6 100644
--- a/Podfile
+++ b/Podfile
@@ -5,24 +5,29 @@ utils_name = 'BuildaUtils'
 utils_version = '0.0.8'

 target 'XcodeServerSDK - OS X' do
+platform :osx, '10.10'
 pod utils_name, utils_version
 end

 target 'XcodeServerSDK - OS X Tests' do
+platform :osx, '10.10'
 pod utils_name, utils_version
 pod 'DVR', :git => "https://github.com/czechboy0/DVR.git", :tag => "v0.0.3-czechboy0"
 end

 target 'XcodeServerSDK - iOS' do
+platform :ios, '8.0'
 pod utils_name, utils_version
 end

 target 'XcodeServerSDK - iOS Tests' do
+platform :ios, '8.0'
 pod utils_name, utils_version
 pod 'DVR', :git => "https://github.com/czechboy0/DVR.git", :tag => "v0.0.3-czechboy0"
 end

 target 'XcodeServerSDK - watchOS' do
+platform :watchos, '2.0'
 pod utils_name, utils_version
 end
```

However, this still doesn't seem to work, because the target dependencies aren't being set up correctly.

**Comment by cojoj** [comment]
And in that case I get `linker command failed...` for OS X while other platforms work as supposed.

**Comment by czechboy0** [comment]
What's the status of this, @cojoj?

**Comment by cojoj** [comment]
Looks like we're stuck... No matter what we put where one platform won't work. I really have no idea what else we can do.

I've tried extracting 

``` ruby
pod utils_name, utils_version
```

outside any `target` but no luck here... 😓

---

I think that right now we're trying to fix issue related to `BuildaUtils`... Maybe fact that we have two targets there or some missing things in `project.pbxproj`.

**Comment by czechboy0** [comment]
`BuildaUtils` shouldn't affect this, it just provides a bunch of `.swift` files, the project file isn't used by CocoaPods AFAIK.

**Comment by czechboy0** [comment]
@neonichu Does this have anything to do with the recent change in CocoaPods in an attempt to reduce duplicate targets? We basically have the same code just compiled for different targets here.

**Comment by neonichu** [comment]
@czechboy0 possibly, I am honestly not sure why exactly it is failing

**Comment by czechboy0** [comment]
:cry: Thanks anyway.

**Comment by czechboy0** [comment]
Closing this due to #110 being merged (so this isn't an issue any more).
